<a href="https://colab.research.google.com/github/abhisheksharma712/employee-turnover-/blob/main/Lasso_ridge_property.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import warnings
warnings.filterwarnings('ignore')

In [19]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [20]:
df=pd.read_csv('/content/property-price.csv')

In [21]:
df.head()

Area (sqr ft)  Bedroom  Age   Price
0           2600      3.0   20  550000
1           3000      4.0   15  565000
2           3200      3.5   18  610000
3           3600      3.0   30  595000
4           4000      5.0    8  760000

In [22]:
df.isnull().sum()

Area (sqr ft)    0
Bedroom          0
Age              0
Price            0
dtype: int64

In [23]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [24]:
model=LinearRegression()
model.fit(X,y)

LinearRegression()

In [25]:
model.coef_

array([    198.47159002, -116583.73881651,  -14267.77585936])

In [26]:
model.intercept_

656046.539004866

In [27]:
model.score(X,y)

0.9812392465259163

In [28]:
# ridge reg
from sklearn.linear_model import Ridge
ridge=Ridge(alpha=0.3)
ridge.fit(X,y)

Ridge(alpha=0.3)

In [29]:
ridge.coef_

array([   136.52364924, -26344.50602124,  -6867.57305968])

In [33]:
ridge.score(X,y)

0.9553804829213461

In [30]:
# lasso reg
from sklearn.linear_model import Lasso
lasso=Lasso(alpha=1.1)
lasso.fit(X,y)

Lasso(alpha=1.1)

In [31]:
lasso.coef_

array([    198.42592913, -116517.15388468,  -14262.29922911])

In [32]:
lasso.score(X,y)

0.9812392324429763